#ifndef TERRAIN_TO_MESH_VARIABLES_CBUFFER_CGINC
#define TERRAIN_TO_MESH_VARIABLES_CBUFFER_CGINC

        //Layer #0
        float4 _T2M_Layer_0_MapsUsage;
        float4 _T2M_Layer_0_MaskMapRemapMin; 
        float4 _T2M_Layer_0_MaskMapRemapMax;
        float4 _T2M_Layer_0_uvScaleOffset;
        float4 _T2M_Layer_0_ColorTint; 
        float4 _T2M_Layer_0_MetallicOcclusionSmoothness;
        int _T2M_Layer_0_SmoothnessFromDiffuseAlpha;
        int _T2M_Layer_0_OpacityAsDensity;
        float _T2M_Layer_0_NormalScale;

        //Layer #1
        float4 _T2M_Layer_1_MapsUsage; 
        float4 _T2M_Layer_1_MaskMapRemapMin; 
        float4 _T2M_Layer_1_MaskMapRemapMax;
        float4 _T2M_Layer_1_uvScaleOffset;
        float4 _T2M_Layer_1_ColorTint;
        float4 _T2M_Layer_1_MetallicOcclusionSmoothness;
        int _T2M_Layer_1_SmoothnessFromDiffuseAlpha;
        int _T2M_Layer_1_OpacityAsDensity;
        float _T2M_Layer_1_NormalScale;
         
        //Layer #2
        float4 _T2M_Layer_2_MapsUsage;
        float4 _T2M_Layer_2_MaskMapRemapMin; 
        float4 _T2M_Layer_2_MaskMapRemapMax;
        float4 _T2M_Layer_2_uvScaleOffset;
        float4 _T2M_Layer_2_ColorTint;
        float4 _T2M_Layer_2_MetallicOcclusionSmoothness;
        int _T2M_Layer_2_SmoothnessFromDiffuseAlpha;
        int _T2M_Layer_2_OpacityAsDensity;
        float _T2M_Layer_2_NormalScale;

        //Layer #3
        float4 _T2M_Layer_3_MapsUsage;
        float4 _T2M_Layer_3_MaskMapRemapMin; 
        float4 _T2M_Layer_3_MaskMapRemapMax;
        float4 _T2M_Layer_3_uvScaleOffset;
        float4 _T2M_Layer_3_ColorTint;
        float4 _T2M_Layer_3_MetallicOcclusionSmoothness;
        int _T2M_Layer_3_SmoothnessFromDiffuseAlpha;
        int _T2M_Layer_3_OpacityAsDensity;
        float _T2M_Layer_3_NormalScale;

        //Layer #4
        float4 _T2M_Layer_4_MapsUsage;
        float4 _T2M_Layer_4_MaskMapRemapMin; 
        float4 _T2M_Layer_4_MaskMapRemapMax;
        float4 _T2M_Layer_4_uvScaleOffset;
        float4 _T2M_Layer_4_ColorTint;
        float4 _T2M_Layer_4_MetallicOcclusionSmoothness;
        int _T2M_Layer_4_SmoothnessFromDiffuseAlpha;
        int _T2M_Layer_4_OpacityAsDensity;
        float _T2M_Layer_4_NormalScale;

        //Layer #5
        float4 _T2M_Layer_5_MapsUsage;
        float4 _T2M_Layer_5_MaskMapRemapMin; 
        float4 _T2M_Layer_5_MaskMapRemapMax;
        float4 _T2M_Layer_5_uvScaleOffset;
        float4 _T2M_Layer_5_ColorTint;
        float4 _T2M_Layer_5_MetallicOcclusionSmoothness;
        int _T2M_Layer_5_SmoothnessFromDiffuseAlpha;
        int _T2M_Layer_5_OpacityAsDensity;
        float _T2M_Layer_5_NormalScale;

        //Layer #6
        float4 _T2M_Layer_6_MapsUsage;
        float4 _T2M_Layer_6_MaskMapRemapMin; 
        float4 _T2M_Layer_6_MaskMapRemapMax;
        float4 _T2M_Layer_6_uvScaleOffset;
        float4 _T2M_Layer_6_ColorTint;
        float4 _T2M_Layer_6_MetallicOcclusionSmoothness;
        int _T2M_Layer_6_SmoothnessFromDiffuseAlpha;
        int _T2M_Layer_6_OpacityAsDensity;
        float _T2M_Layer_6_NormalScale;

        //Layer #7
        float4 _T2M_Layer_7_MapsUsage;
        float4 _T2M_Layer_7_MaskMapRemapMin; 
        float4 _T2M_Layer_7_MaskMapRemapMax;
        float4 _T2M_Layer_7_uvScaleOffset;
        float4 _T2M_Layer_7_ColorTint;
        float4 _T2M_Layer_7_MetallicOcclusionSmoothness;
        int _T2M_Layer_7_SmoothnessFromDiffuseAlpha;
        int _T2M_Layer_7_OpacityAsDensity;
        float _T2M_Layer_7_NormalScale;

        //Layer #8
        float4 _T2M_Layer_8_MapsUsage;
        float4 _T2M_Layer_8_MaskMapRemapMin; 
        float4 _T2M_Layer_8_MaskMapRemapMax;
        float4 _T2M_Layer_8_uvScaleOffset;
        float4 _T2M_Layer_8_ColorTint;
        float4 _T2M_Layer_8_MetallicOcclusionSmoothness;
        int _T2M_Layer_8_SmoothnessFromDiffuseAlpha;
        int _T2M_Layer_8_OpacityAsDensity;
        float _T2M_Layer_8_NormalScale;

        //Layer #9
        float4 _T2M_Layer_9_MapsUsage;
        float4 _T2M_Layer_9_MaskMapRemapMin; 
        float4 _T2M_Layer_9_MaskMapRemapMax;
        float4 _T2M_Layer_9_uvScaleOffset;
        float4 _T2M_Layer_9_ColorTint;
        float4 _T2M_Layer_9_MetallicOcclusionSmoothness;
        int _T2M_Layer_9_SmoothnessFromDiffuseAlpha;
        int _T2M_Layer_9_OpacityAsDensity;
        float _T2M_Layer_9_NormalScale;

        //Layer #10
        float4 _T2M_Layer_10_MapsUsage;
        float4 _T2M_Layer_10_MaskMapRemapMin; 
        float4 _T2M_Layer_10_MaskMapRemapMax;
        float4 _T2M_Layer_10_uvScaleOffset;
        float4 _T2M_Layer_10_ColorTint;
        float4 _T2M_Layer_10_MetallicOcclusionSmoothness;
        int _T2M_Layer_10_SmoothnessFromDiffuseAlpha;
        int _T2M_Layer_10_OpacityAsDensity;
        float _T2M_Layer_10_NormalScale;

        //Layer #11
        float4 _T2M_Layer_11_MapsUsage;
        float4 _T2M_Layer_11_MaskMapRemapMin; 
        float4 _T2M_Layer_11_MaskMapRemapMax;
        float4 _T2M_Layer_11_uvScaleOffset;
        float4 _T2M_Layer_11_ColorTint;
        float4 _T2M_Layer_11_MetallicOcclusionSmoothness;
        int _T2M_Layer_11_SmoothnessFromDiffuseAlpha;
        int _T2M_Layer_11_OpacityAsDensity;
        float _T2M_Layer_11_NormalScale;

        //Layer #12
        float4 _T2M_Layer_12_MapsUsage;
        float4 _T2M_Layer_12_MaskMapRemapMin; 
        float4 _T2M_Layer_12_MaskMapRemapMax;
        float4 _T2M_Layer_12_uvScaleOffset;
        float4 _T2M_Layer_12_ColorTint;
        float4 _T2M_Layer_12_MetallicOcclusionSmoothness;
        int _T2M_Layer_12_SmoothnessFromDiffuseAlpha;
        int _T2M_Layer_12_OpacityAsDensity;
        float _T2M_Layer_12_NormalScale;

        //Layer #13
        float4 _T2M_Layer_13_MapsUsage;
        float4 _T2M_Layer_13_MaskMapRemapMin;  
        float4 _T2M_Layer_13_MaskMapRemapMax;
        float4 _T2M_Layer_13_uvScaleOffset; 
        float4 _T2M_Layer_13_ColorTint;
        float4 _T2M_Layer_13_MetallicOcclusionSmoothness;
        int _T2M_Layer_13_SmoothnessFromDiffuseAlpha;
        int _T2M_Layer_13_OpacityAsDensity;
        float _T2M_Layer_13_NormalScale;

        //Layer #14
        float4 _T2M_Layer_14_MapsUsage;
        float4 _T2M_Layer_14_MaskMapRemapMin; 
        float4 _T2M_Layer_14_MaskMapRemapMax;
        float4 _T2M_Layer_14_uvScaleOffset;
        float4 _T2M_Layer_14_ColorTint;
        float4 _T2M_Layer_14_MetallicOcclusionSmoothness;
        int _T2M_Layer_14_SmoothnessFromDiffuseAlpha;
        int _T2M_Layer_14_OpacityAsDensity;
        float _T2M_Layer_14_NormalScale;

        //Layer #15
        float4 _T2M_Layer_15_MapsUsage;
        float4 _T2M_Layer_15_MaskMapRemapMin; 
        float4 _T2M_Layer_15_MaskMapRemapMax;
        float4 _T2M_Layer_15_uvScaleOffset;
        float4 _T2M_Layer_15_ColorTint;
        float4 _T2M_Layer_15_MetallicOcclusionSmoothness;
        int _T2M_Layer_15_SmoothnessFromDiffuseAlpha;
        int _T2M_Layer_15_OpacityAsDensity;
        float _T2M_Layer_15_NormalScale;

#endif  //TERRAIN_TO_MESH_VARIABLES_CBUFFER_CGINC
